// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: kvsService.proto
#ifndef GRPC_kvsService_2eproto__INCLUDED
#define GRPC_kvsService_2eproto__INCLUDED

#include "kvsService.pb.h"

#include <functional>
#include <grpc/impl/codegen/port_platform.h>
#include <grpcpp/impl/codegen/async_generic_service.h>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/client_context.h>
#include <grpcpp/impl/codegen/completion_queue.h>
#include <grpcpp/impl/codegen/message_allocator.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/proto_utils.h>
#include <grpcpp/impl/codegen/rpc_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/status.h>
#include <grpcpp/impl/codegen/stub_options.h>
#include <grpcpp/impl/codegen/sync_stream.h>

class kvsService final {
 public:
  static constexpr char const* service_full_name() {
    return "kvsService";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status kvsPut(::grpc::ClientContext* context, const ::putRequest& request, ::putResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::putResponse>> AsynckvsPut(::grpc::ClientContext* context, const ::putRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::putResponse>>(AsynckvsPutRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::putResponse>> PrepareAsynckvsPut(::grpc::ClientContext* context, const ::putRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::putResponse>>(PrepareAsynckvsPutRaw(context, request, cq));
    }
    virtual ::grpc::Status kvsGet(::grpc::ClientContext* context, const ::getRequest& request, ::getResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::getResponse>> AsynckvsGet(::grpc::ClientContext* context, const ::getRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::getResponse>>(AsynckvsGetRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::getResponse>> PrepareAsynckvsGet(::grpc::ClientContext* context, const ::getRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::getResponse>>(PrepareAsynckvsGetRaw(context, request, cq));
    }
    class experimental_async_interface {
     public:
      virtual ~experimental_async_interface() {}
      virtual void kvsPut(::grpc::ClientContext* context, const ::putRequest* request, ::putResponse* response, std::function<void(::grpc::Status)>) = 0;
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      virtual void kvsPut(::grpc::ClientContext* context, const ::putRequest* request, ::putResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      #else
      virtual void kvsPut(::grpc::ClientContext* context, const ::putRequest* request, ::putResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) = 0;
      #endif
      virtual void kvsGet(::grpc::ClientContext* context, const ::getRequest* request, ::getResponse* response, std::function<void(::grpc::Status)>) = 0;
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      virtual void kvsGet(::grpc::ClientContext* context, const ::getRequest* request, ::getResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      #else
      virtual void kvsGet(::grpc::ClientContext* context, const ::getRequest* request, ::getResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) = 0;
      #endif
    };
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    typedef class experimental_async_interface async_interface;
    #endif
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    async_interface* async() { return experimental_async(); }
    #endif
    virtual class experimental_async_interface* experimental_async() { return nullptr; }
  private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::putResponse>* AsynckvsPutRaw(::grpc::ClientContext* context, const ::putRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::putResponse>* PrepareAsynckvsPutRaw(::grpc::ClientContext* context, const ::putRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::getResponse>* AsynckvsGetRaw(::grpc::ClientContext* context, const ::getRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::getResponse>* PrepareAsynckvsGetRaw(::grpc::ClientContext* context, const ::getRequest& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel);
    ::grpc::Status kvsPut(::grpc::ClientContext* context, const ::putRequest& request, ::putResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::putResponse>> AsynckvsPut(::grpc::ClientContext* context, const ::putRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::putResponse>>(AsynckvsPutRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::putResponse>> PrepareAsynckvsPut(::grpc::ClientContext* context, const ::putRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::putResponse>>(PrepareAsynckvsPutRaw(context, request, cq));
    }
    ::grpc::Status kvsGet(::grpc::ClientContext* context, const ::getRequest& request, ::getResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::getResponse>> AsynckvsGet(::grpc::ClientContext* context, const ::getRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::getResponse>>(AsynckvsGetRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::getResponse>> PrepareAsynckvsGet(::grpc::ClientContext* context, const ::getRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::getResponse>>(PrepareAsynckvsGetRaw(context, request, cq));
    }
    class experimental_async final :
      public StubInterface::experimental_async_interface {
     public:
      void kvsPut(::grpc::ClientContext* context, const ::putRequest* request, ::putResponse* response, std::function<void(::grpc::Status)>) override;
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      void kvsPut(::grpc::ClientContext* context, const ::putRequest* request, ::putResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
      #else
      void kvsPut(::grpc::ClientContext* context, const ::putRequest* request, ::putResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) override;
      #endif
      void kvsGet(::grpc::ClientContext* context, const ::getRequest* request, ::getResponse* response, std::function<void(::grpc::Status)>) override;
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      void kvsGet(::grpc::ClientContext* context, const ::getRequest* request, ::getResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
      #else
      void kvsGet(::grpc::ClientContext* context, const ::getRequest* request, ::getResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) override;
      #endif
     private:
      friend class Stub;
      explicit experimental_async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class experimental_async_interface* experimental_async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class experimental_async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::putResponse>* AsynckvsPutRaw(::grpc::ClientContext* context, const ::putRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::putResponse>* PrepareAsynckvsPutRaw(::grpc::ClientContext* context, const ::putRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::getResponse>* AsynckvsGetRaw(::grpc::ClientContext* context, const ::getRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::getResponse>* PrepareAsynckvsGetRaw(::grpc::ClientContext* context, const ::getRequest& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_kvsPut_;
    const ::grpc::internal::RpcMethod rpcmethod_kvsGet_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status kvsPut(::grpc::ServerContext* context, const ::putRequest* request, ::putResponse* response);
    virtual ::grpc::Status kvsGet(::grpc::ServerContext* context, const ::getRequest* request, ::getResponse* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_kvsPut : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_kvsPut() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_kvsPut() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status kvsPut(::grpc::ServerContext* /*context*/, const ::putRequest* /*request*/, ::putResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestkvsPut(::grpc::ServerContext* context, ::putRequest* request, ::grpc::ServerAsyncResponseWriter< ::putResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_kvsGet : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_kvsGet() {
      ::grpc::Service::MarkMethodAsync(1);
    }
    ~WithAsyncMethod_kvsGet() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status kvsGet(::grpc::ServerContext* /*context*/, const ::getRequest* /*request*/, ::getResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestkvsGet(::grpc::ServerContext* context, ::getRequest* request, ::grpc::ServerAsyncResponseWriter< ::getResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_kvsPut<WithAsyncMethod_kvsGet<Service > > AsyncService;
  template <class BaseClass>
  class ExperimentalWithCallbackMethod_kvsPut : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    ExperimentalWithCallbackMethod_kvsPut() {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::Service::
    #else
      ::grpc::Service::experimental().
    #endif
        MarkMethodCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::putRequest, ::putResponse>(
            [this](
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
                   ::grpc::CallbackServerContext*
    #else
                   ::grpc::experimental::CallbackServerContext*
    #endif
                     context, const ::putRequest* request, ::putResponse* response) { return this->kvsPut(context, request, response); }));}
    void SetMessageAllocatorFor_kvsPut(
        ::grpc::experimental::MessageAllocator< ::putRequest, ::putResponse>* allocator) {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
    #else
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::experimental().GetHandler(0);
    #endif
      static_cast<::grpc::internal::CallbackUnaryHandler< ::putRequest, ::putResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~ExperimentalWithCallbackMethod_kvsPut() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status kvsPut(::grpc::ServerContext* /*context*/, const ::putRequest* /*request*/, ::putResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    virtual ::grpc::ServerUnaryReactor* kvsPut(
      ::grpc::CallbackServerContext* /*context*/, const ::putRequest* /*request*/, ::putResponse* /*response*/)
    #else
    virtual ::grpc::experimental::ServerUnaryReactor* kvsPut(
      ::grpc::experimental::CallbackServerContext* /*context*/, const ::putRequest* /*request*/, ::putResponse* /*response*/)
    #endif
      { return nullptr; }
  };
  template <class BaseClass>
  class ExperimentalWithCallbackMethod_kvsGet : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    ExperimentalWithCallbackMethod_kvsGet() {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::Service::
    #else
      ::grpc::Service::experimental().
    #endif
        MarkMethodCallback(1,
          new ::grpc::internal::CallbackUnaryHandler< ::getRequest, ::getResponse>(
            [this](
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
                   ::grpc::CallbackServerContext*
    #else
                   ::grpc::experimental::CallbackServerContext*
    #endif
                     context, const ::getRequest* request, ::getResponse* response) { return this->kvsGet(context, request, response); }));}
    void SetMessageAllocatorFor_kvsGet(
        ::grpc::experimental::MessageAllocator< ::getRequest, ::getResponse>* allocator) {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(1);
    #else
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::experimental().GetHandler(1);
    #endif
      static_cast<::grpc::internal::CallbackUnaryHandler< ::getRequest, ::getResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~ExperimentalWithCallbackMethod_kvsGet() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status kvsGet(::grpc::ServerContext* /*context*/, const ::getRequest* /*request*/, ::getResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    virtual ::grpc::ServerUnaryReactor* kvsGet(
      ::grpc::CallbackServerContext* /*context*/, const ::getRequest* /*request*/, ::getResponse* /*response*/)
    #else
    virtual ::grpc::experimental::ServerUnaryReactor* kvsGet(
      ::grpc::experimental::CallbackServerContext* /*context*/, const ::getRequest* /*request*/, ::getResponse* /*response*/)
    #endif
      { return nullptr; }
  };
  #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
  typedef ExperimentalWithCallbackMethod_kvsPut<ExperimentalWithCallbackMethod_kvsGet<Service > > CallbackService;
  #endif

  typedef ExperimentalWithCallbackMethod_kvsPut<ExperimentalWithCallbackMethod_kvsGet<Service > > ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_kvsPut : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_kvsPut() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_kvsPut() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status kvsPut(::grpc::ServerContext* /*context*/, const ::putRequest* /*request*/, ::putResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_kvsGet : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_kvsGet() {
      ::grpc::Service::MarkMethodGeneric(1);
    }
    ~WithGenericMethod_kvsGet() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status kvsGet(::grpc::ServerContext* /*context*/, const ::getRequest* /*request*/, ::getResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_kvsPut : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_kvsPut() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_kvsPut() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status kvsPut(::grpc::ServerContext* /*context*/, const ::putRequest* /*request*/, ::putResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestkvsPut(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_kvsGet : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_kvsGet() {
      ::grpc::Service::MarkMethodRaw(1);
    }
    ~WithRawMethod_kvsGet() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status kvsGet(::grpc::ServerContext* /*context*/, const ::getRequest* /*request*/, ::getResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestkvsGet(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class ExperimentalWithRawCallbackMethod_kvsPut : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    ExperimentalWithRawCallbackMethod_kvsPut() {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::Service::
    #else
      ::grpc::Service::experimental().
    #endif
        MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
                   ::grpc::CallbackServerContext*
    #else
                   ::grpc::experimental::CallbackServerContext*
    #endif
                     context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->kvsPut(context, request, response); }));
    }
    ~ExperimentalWithRawCallbackMethod_kvsPut() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status kvsPut(::grpc::ServerContext* /*context*/, const ::putRequest* /*request*/, ::putResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    virtual ::grpc::ServerUnaryReactor* kvsPut(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)
    #else
    virtual ::grpc::experimental::ServerUnaryReactor* kvsPut(
      ::grpc::experimental::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)
    #endif
      { return nullptr; }
  };
  template <class BaseClass>
  class ExperimentalWithRawCallbackMethod_kvsGet : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    ExperimentalWithRawCallbackMethod_kvsGet() {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::Service::
    #else
      ::grpc::Service::experimental().
    #endif
        MarkMethodRawCallback(1,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
                   ::grpc::CallbackServerContext*
    #else
                   ::grpc::experimental::CallbackServerContext*
    #endif
                     context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->kvsGet(context, request, response); }));
    }
    ~ExperimentalWithRawCallbackMethod_kvsGet() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status kvsGet(::grpc::ServerContext* /*context*/, const ::getRequest* /*request*/, ::getResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    virtual ::grpc::ServerUnaryReactor* kvsGet(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)
    #else
    virtual ::grpc::experimental::ServerUnaryReactor* kvsGet(
      ::grpc::experimental::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)
    #endif
      { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_kvsPut : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_kvsPut() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::putRequest, ::putResponse>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::putRequest, ::putResponse>* streamer) {
                       return this->StreamedkvsPut(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_kvsPut() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status kvsPut(::grpc::ServerContext* /*context*/, const ::putRequest* /*request*/, ::putResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedkvsPut(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::putRequest,::putResponse>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_kvsGet : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_kvsGet() {
      ::grpc::Service::MarkMethodStreamed(1,
        new ::grpc::internal::StreamedUnaryHandler<
          ::getRequest, ::getResponse>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::getRequest, ::getResponse>* streamer) {
                       return this->StreamedkvsGet(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_kvsGet() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status kvsGet(::grpc::ServerContext* /*context*/, const ::getRequest* /*request*/, ::getResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedkvsGet(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::getRequest,::getResponse>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_kvsPut<WithStreamedUnaryMethod_kvsGet<Service > > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_kvsPut<WithStreamedUnaryMethod_kvsGet<Service > > StreamedService;
};


#endif  // GRPC_kvsService_2eproto__INCLUDED
